#! /usr/bin/env python

'''usage: bsd-cloudint'''

from cloudbaseinit.metadata import factory as metadata_factory
from cloudbaseinit.openstack.common import log as logging
from cloudbaseinit.osutils import factory as osutils_factory
from cloudbaseinit.plugins import base as plugins_base
from cloudbaseinit.plugins import factory as plugins_factory

LOG = logging.getLogger(__name__)

osutils = osutils_factory.OSUtilsFactory().get_os_utils()
print osutils

# choose meta data service "httpservice"
mdsf = metadata_factory.MetadataServiceFactory()
service = mdsf.get_metadata_service()
LOG.info('Metadata service loaded: \'%s\'' % service.get_name())

# test get meta data
print('get name =>', service.get_name())
#print('get user data =>', service.get_user_data('openstack'))
print('get meta data =>', service.get_meta_data('openstack'))

# load plugins
plugins = plugins_factory.PluginFactory().load_plugins()

# running each plugins ?
for plugin in plugins:

    print '='*20

    print plugin

    print plugin.get_name()
    plugin_name = plugin.get_name()

    print plugin.get_os_requirements()

    print osutils.get_config_value(plugin_name,'Plugins')

    try:
        print plugin.execute(service)
    except:
        print 'fail Q_Qa'

